namespace VM;

public enum OpCode : byte {
    Push,
    Pop,
    Lit,
    PushContinuationForArg,
    PushContinuationForNonTailBody,
    PopContinuation,
    Call,
    Top,
    SetTop,
    Arg,
    DefArg,
    DefVar,
    SetArg,
    Lex,
    SetLex,
    // Bind,
    // BindRest,
    Jump,
    JumpIfFalse,
    Env,
    Lambda,
    Sum,
    Product,
    CallCC,
    CallWValues,
    PushWinder,
    PushContinuationForBodyThunk,
    PopWinder,
    PushFP,
    SPToFP,
    PopFP,
    ArgToArgs, // takes list arg from stack and pushes each element onto stack. TODO: yuck
    Halt,
    // MkLoc
}