namespace VM;

public enum OpCode : byte {
    Push,
    Pop,
    Lit,
    PushContinuationForArg,
    PushContinuationForNonTailBody,
    PopContinuationDB,
    PopContinuation,
    CallDB,
    Call,
    Var,
    SetVar,
    Arg,
    SetArg,
    Jump,
    JumpIfFalse,
    Env,
    Lambda,
    CallCC,
    CallWValues,
    PushWinder,
    PushContinuationForBodyThunk,
    PopWinder,
    PushFP,
    SPToFP,
    PopFP,
    ArgToArgs, // takes list arg from stack and pushes each element onto stack. TODO: yuck
    Halt,
}